defaults:
  - override hydra/launcher: submitit_slurm
#  - override hydra/launcher: submitit_local
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  launcher:
    account: renard
    timeout_min: 7200
    partition: magic
    mem_gb: 40
    nodes: 3
    tasks_per_node: 10
    cpus_per_task: 12
    stderr_to_stdout: true
    name: hydra
  sweeper:
    n_trials: 100
    n_jobs: 10
    direction: maximize
    params:
      classifier: choice(None)
      model: choice(None)
      n_jobs: choice(1)
      x_train: choice(None)
      y_train: choice(None)

classifier: 1
model: 1
n_jobs: 1
x_train: 1
y_train: 1
