defaults:
#  - override hydra/launcher: submitit_slurm
  - override hydra/launcher: submitit_local
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  launcher:
    mem_gb: 450
#    account: renard
    timeout_min: 1440
#    partition: magic
  sweeper:
    n_trials: 5
    n_jobs: 256
    direction: maximize
    sampler:
      seed: 42
