defaults:
  - override hydra/launcher: submitit_slurm  # uncomment this line to run on slurm
#  - override hydra/launcher: submitit_local  # uncomment this line to run locally
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  launcher:
    mem_gb: 450
    account: renard  # uncomment this line to run on slurm
    timeout_min: 4320
    partition: magic  # uncomment this line to run on slurm
  sweeper:
    n_trials: 1000
    n_jobs: 21
    direction: maximize
    params:
      classifier: choice(None)
      model: choice(None)
      n_jobs: choice(1)
      x_train: choice(None)
      y_train: choice(None)
      scripts_dir: choice(None)

classifier: 1
model: 1
n_jobs: 1
x_train: 1
y_train: 1
scripts_dir: 1
