defaults:
#  - override hydra/launcher: submitit_slurm  # uncomment this line to run on slurm
  - override hydra/launcher: submitit_local  # uncomment this line to run locally
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  launcher:
    mem_gb: 450
#    account: renard  # uncomment this line to run on slurm
    timeout_min: 1440
#    partition: magic  # uncomment this line to run on slurm
  sweeper:
    n_trials: 5
    n_jobs: 256
    direction: maximize
