defaults:
  - _self_
  - optuna
  - submitit

hydra:
  sweeper:
    params:
      num_leaves: choice(31, 62, 124)
      n_estimators: choice(100, 500, 1000)
      min_child_samples: choice(20, 40, 60)

num_leaves: 1
n_estimators: 1
min_child_samples: 1
