defaults:
  - _self_
  - optuna
  - submitit

hydra:
  sweeper:
    params:
      n_estimators: choice(100, 500, 1000)
      criterion: choice("gini", "entropy", "log_loss")

n_estimators: 1
criterion: 1
