workdir: /home/fabio/Desktop/hiclass/benchmarks/consumer_complaints

threads: 12

data: 'https://files.consumerfinance.gov/ccdb/complaints.csv.zip'

random_state: 42

# Memory allocated for tune and train rules
mem_gb: 450

# Uncomment the next line to use a subset of the data
nrows: 1000

classifiers:
  - logistic_regression
  - random_forest
  - lightgbm

models:
  - flat
  - local_classifier_per_node
  - local_classifier_per_parent_node
  - local_classifier_per_level
